server:
  port: 8410
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/oasys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Caiyd.
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  cache:
    type: redis
    cache-names: permission-role
  redis:
    host: tbigdata02.gz.batmobi.cn
    port: 6379
    password: Bigdata#321