server:
  port: 8450
spring:
  application:
    name: chat-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    mongodb:
      host: 192.168.1.15
      port: 27017
      database: chat_record
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  kafka:
    consumer:
      group-id: chat
      auto-offset-reset: earliest
      bootstrap-servers: 192.168.1.15:9092